version: "3"
services:
  db:
    image: postgres:13.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: bootcamp_luminus_dev
