version: "3"
services:
  db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: bootcamp_luminus_test
